### ISSUE TITLE
版本更新

### ISSUE THREAD

**Issue by shanshenbing** [YuanchenZhu2020/R_Packages_zh_CN#1]
https://r-pkgs.org/introduction.html 已经出了新版本了，可以考虑直接谷歌翻译+自己再修改一下。

**Comment by YuanchenZhu2020** [comment]
感谢提醒~
抱歉没有及时回复，我的邮箱将通知邮件当作垃圾邮件了

**Comment by YuanchenZhu2020** [comment]
感谢提醒~重新翻译正在计划中。
抱歉没有及时回复，我的邮箱将通知邮件当作垃圾邮件了
